### ISSUE TITLE
Error while using hello-data.js

### ISSUE THREAD

**Issue by kokyeesiang** [qlik-oss/core-get-started#239]
### Description

Get an Error when loading "hello-data".

### Steps to Reproduce

Just followed the Guide on the Qlikcore Getting Started Website
https://core.qlik.com/tutorials/hello-data/

##### Expected behavior
The output from the "hello-data" guide

$ npm run hello-data
Creating table data representation.
Creating and opening session using mixin.
Creating session object with movie titles.
Listing the 10 first movies:
2012
Armageddon
Avatar
Battleship
Cars 2
Cleopatra
Evan Almighty
Green Lantern
Harry Potter and the Half-Blood Prince
Indiana Jones and the Kingdom of the Crystal Skull
Session closed.

##### Actual behavior

> node ./src/hello-data/hello-data.js

Creating session app on engine.
Creating data connection to local files.
Whoops! An error occurred. { Error: Invalid path
    at Intercept.errorInterceptor (C:\Project\QlikCore_data\core-get-started-master\node_modules\enigma.js\enigma.js:2549:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7) code: 4, parameter: 'Invalid path' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core-get-started@0.0.1 hello-data: `node ./src/hello-data/hello-data.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the core-get-started@0.0.1 hello-data script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abs\AppData\Roaming\npm-cache\_logs\2019-03-20T07_46_41_306Z-debug.log

##### Library
```
[x] Node.js
[ ] Browser
```
##### Operating system
```
[x] Windows
[ ] OSX
[ ] Linux
```
### Versions

* Node.js: v11.6.0
* Browser: Google Chrome 72.0.3626.121
* Operating system: Windows 10

I am looking for someone that can help me since always getting this error in the Getting Started guide from Qlik Core. I try to run the "hello-data.js" but always get the Error Message above.

**Comment by wennmo** [comment]
Hello @kokyeesiang, from the log it looks like Engine is unable to find the mounted volume. Can you check that you are sharing the drive with Docker for Windows?

You can find the setting in Docker for Windows -> Settings -> Shared Drives

**Comment by kokyeesiang** [comment]
Hi @wennmo , 
![image](https://user-images.githubusercontent.com/47622097/54729850-aaa11c00-4bc0-11e9-893c-c6e0c7af0c57.png)
Already shared in the setting in Docker fyi but still hit the error.

**Comment by wennmo** [comment]
Hi @kokyeesiang ,
Can you attach the docker logs from the engine container?

Run `docker ps` and you will get an output of running containers on your machine. Then use the `CONTAINER ID` when fetching the logs e.g. `docker logs <CONTAINER ID>`.

You can also check if the file `movies.csv` was successfully mounted into the engine container by running `docker exec -it <CONTAINER ID> sh -c "ls /data"`.

**Comment by kokyeesiang** [comment]
Hi @wennmo ,

docker logs:
PS C:\Project\QlikCore_data\core-get-started-master> docker logs 8c0838f58783
{"timestamp":"2019-03-21T01:59:33.645Z","log_type":"System","logseverity":"INFO","thread_id":2116521664,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"Engine started with command line: --MigrationPort -1 -S QvLogUseStdoutLogger=1 -S QvLogHandleRequestOnExit=1 -S AllowExternalSocket=1 -S EnableSwagger=1 -S EnablePrometheus=1 -S PrometheusServicePort=9090 -S PerformanceLogVerbosity=0 -S UseCGroupsStats=1 -S AdjustMemUseFromOs=0 -S EnableCrashDump=1 -S EnableScriptLogging=2 -S AcceptEULA=yes "}
{"timestamp":"2019-03-21T01:59:33.701Z","log_type":"Start","logseverity":"INFO","thread_id":2116521664,"message":"Invalid parameter handler set"}
{"timestamp":"2019-03-21T01:59:33.701Z","log_type":"Start","logseverity":"INFO","thread_id":2116521664,"message":"ComputerName is 8c0838f58783"}
{"timestamp":"2019-03-21T01:59:33.701Z","log_type":"Start","logseverity":"INFO","thread_id":2116521664,"message":"Engine Version is 12.345.0"}
{"timestamp":"2019-03-21T01:59:33.859Z","log_type":"Start","logseverity":"INFO","thread_id":2116521664,"message":"Locale(s) set"}
{"timestamp":"2019-03-21T01:59:33.859Z","log_type":"Start","logseverity":"INFO","thread_id":2116521664,"message":"QHeap initialized"}
{"timestamp":"2019-03-21T01:59:33.860Z","log_type":"Start","logseverity":"INFO","thread_id":2116521664,"message":"Running in desktop mode"}
{"timestamp":"2019-03-21T01:59:34.075Z","log_type":"Start","logseverity":"INFO","thread_id":2116521664,"message":"Initiating server license."}
{"timestamp":"2019-03-21T01:59:34.100Z","log_type":"System","logseverity":"INFO","thread_id":2116521664,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"GlobalContext: Initiating Broker default port 4848"}
{"timestamp":"2019-03-21T01:59:34.100Z","log_type":"System","logseverity":"INFO","thread_id":2116521664,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"GlobalContext: Initiating DataPrepPort default port 9072"}
{"timestamp":"2019-03-21T01:59:34.108Z","log_type":"System","logseverity":"INFO","thread_id":2116521664,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"WorkingSet: Configured Working Set Size is 1.354-1.741 GB (setting 70%-90%)"}
{"timestamp":"2019-03-21T01:59:34.111Z","log_type":"Start","logseverity":"INFO","thread_id":2116521664,"message":"Initiating ExtEngine."}
{"timestamp":"2019-03-21T01:59:34.114Z","log_type":"Start","logseverity":"INFO","thread_id":2116521664,"message":"Initialization complete."}
{"timestamp":"2019-03-21T01:59:34.126Z","log_type":"System","logseverity":"INFO","thread_id":2116521664,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"QvSocket: Starting HTTP request handler - 0x7f957b360a20"}
{"timestamp":"2019-03-21T01:59:34.133Z","log_type":"System","logseverity":"INFO","thread_id":2116521664,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"Port Listen: IPv4 bind successful on Port 9076"}
{"timestamp":"2019-03-21T01:59:34.133Z","log_type":"System","logseverity":"INFO","thread_id":2116521664,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"Port Listen: IPv6 bind successful on Port 9076"}
{"timestamp":"2019-03-21T01:59:34.134Z","log_type":"System","logseverity":"INFO","thread_id":2116521664,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"System: Starting - Purge: Starting"}
{"timestamp":"2019-03-21T01:59:34.135Z","log_type":"System","logseverity":"INFO","thread_id":2116521664,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"System: Starting - ServerWatchDog: Starting"}
{"timestamp":"2019-03-21T01:59:35.136Z","log_type":"System","logseverity":"INFO","thread_id":2033415936,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"Mount: Found Mount  at location /home/nobody/Qlik/Sense/Apps  browsable"}
{"timestamp":"2019-03-21T02:00:22.150Z","log_type":"System","logseverity":"INFO","thread_id":1778366208,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"TheServer: Registering new server session"}
{"timestamp":"2019-03-21T02:00:22.151Z","log_type":"System","logseverity":"INFO","thread_id":1778366208,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"QvSocket: Connected to server as user: 'Personal\\Me' for document: '/app/' on socket 172.17.0.2:9076 <-> 172.17.0.1:53020 with ttl: 0"}
{"timestamp":"2019-03-21T02:00:22.349Z","log_type":"System","logseverity":"INFO","thread_id":1795151616,"user_id":"Personal\\Me","tenant_id":"default","app_id":"0","message":"DOC loading: Loaded session app SessionApp_e8b94e67-e52c-4670-94c9-302a0002c7ff."}
{"timestamp":"2019-03-21T02:00:22.671Z","log_type":"System","logseverity":"INFO","thread_id":1778366208,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"StdServer: OnRemoteClosed entered for socket 172.17.0.2:9076 <-> 172.17.0.1:53020, user: Personal\\Me, app: SessionApp_e8b94e67-e52c-4670-94c9-302a0002c7ff."}
{"timestamp":"2019-03-21T02:00:22.671Z","log_type":"System","logseverity":"INFO","thread_id":2033415936,"user_id":"Personal\\Me","tenant_id":"default","app_id":"","message":"Session stop reason: Socket closed by client"}
{"timestamp":"2019-03-21T02:00:24.179Z","log_type":"System","logseverity":"INFO","thread_id":2033415936,"user_id":"Personal\\Me","tenant_id":"","app_id":"","message":"DOC loading: Unloading document SessionApp_e8b94e67-e52c-4670-94c9-302a0002c7ff, state UNLOADING."}
{"timestamp":"2019-03-21T02:02:14.901Z","log_type":"System","logseverity":"INFO","thread_id":1778366208,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"TheServer: Registering new server session"}
{"timestamp":"2019-03-21T02:02:14.901Z","log_type":"System","logseverity":"INFO","thread_id":1778366208,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"QvSocket: Connected to server as user: 'Personal\\Me' for document: '/app/' on socket 172.17.0.2:9076 <-> 172.17.0.1:53022 with ttl: 0"}
{"timestamp":"2019-03-21T02:02:14.912Z","log_type":"System","logseverity":"INFO","thread_id":1795151616,"user_id":"Personal\\Me","tenant_id":"default","app_id":"0","message":"DOC loading: Loaded session app SessionApp_b773bcdf-f2c3-41b5-887f-b219eb64ef57."}
{"timestamp":"2019-03-21T02:02:14.938Z","log_type":"System","logseverity":"INFO","thread_id":1778366208,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"StdServer: OnRemoteClosed entered for socket 172.17.0.2:9076 <-> 172.17.0.1:53022, user: Personal\\Me, app: SessionApp_b773bcdf-f2c3-41b5-887f-b219eb64ef57."}
{"timestamp":"2019-03-21T02:02:14.938Z","log_type":"System","logseverity":"INFO","thread_id":2033415936,"user_id":"Personal\\Me","tenant_id":"default","app_id":"","message":"Session stop reason: Socket closed by client"}
{"timestamp":"2019-03-21T02:02:24.230Z","log_type":"System","logseverity":"INFO","thread_id":2033415936,"user_id":"Personal\\Me","tenant_id":"","app_id":"","message":"DOC loading: Unloading document SessionApp_b773bcdf-f2c3-41b5-887f-b219eb64ef57, state UNLOADING."}
{"timestamp":"2019-03-21T02:59:34.481Z","log_type":"System","logseverity":"INFO","thread_id":1769973504,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"System: Starting purge of temporary files."}
{"timestamp":"2019-03-21T03:59:35.477Z","log_type":"System","logseverity":"INFO","thread_id":1769973504,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"System: Starting purge of temporary files."}
{"timestamp":"2019-03-21T04:59:36.433Z","log_type":"System","logseverity":"INFO","thread_id":1769973504,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"System: Starting purge of temporary files."}
{"timestamp":"2019-03-21T05:59:37.186Z","log_type":"System","logseverity":"INFO","thread_id":1769973504,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"System: Starting purge of temporary files."}
{"timestamp":"2019-03-21T06:48:24.011Z","log_type":"System","logseverity":"INFO","thread_id":1778366208,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"TheServer: Registering new server session"}
{"timestamp":"2019-03-21T06:48:24.012Z","log_type":"System","logseverity":"INFO","thread_id":1778366208,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"QvSocket: Connected to server as user: 'Personal\\Me' for document: '/app/' on socket 172.17.0.2:9076 <-> 172.17.0.1:53060 with ttl: 0"}
{"timestamp":"2019-03-21T06:48:24.025Z","log_type":"System","logseverity":"INFO","thread_id":1795151616,"user_id":"Personal\\Me","tenant_id":"default","app_id":"0","message":"DOC loading: Loaded session app SessionApp_c75ec487-6854-44e9-997b-c8e6543297fe."}
{"timestamp":"2019-03-21T06:48:24.051Z","log_type":"System","logseverity":"INFO","thread_id":1778366208,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"StdServer: OnRemoteClosed entered for socket 172.17.0.2:9076 <-> 172.17.0.1:53060, user: Personal\\Me, app: SessionApp_c75ec487-6854-44e9-997b-c8e6543297fe."}
{"timestamp":"2019-03-21T06:48:24.052Z","log_type":"System","logseverity":"INFO","thread_id":2033415936,"user_id":"Personal\\Me","tenant_id":"default","app_id":"","message":"Session stop reason: Socket closed by client"}
{"timestamp":"2019-03-21T06:48:33.862Z","log_type":"System","logseverity":"INFO","thread_id":2033415936,"user_id":"Personal\\Me","tenant_id":"","app_id":"","message":"DOC loading: Unloading document SessionApp_c75ec487-6854-44e9-997b-c8e6543297fe, state UNLOADING."}
{"timestamp":"2019-03-21T06:59:37.308Z","log_type":"System","logseverity":"INFO","thread_id":1769973504,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"System: Starting purge of temporary files."}
{"timestamp":"2019-03-21T07:48:22.655Z","log_type":"System","logseverity":"INFO","thread_id":1778366208,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"TheServer: Registering new server session"}
{"timestamp":"2019-03-21T07:48:22.655Z","log_type":"System","logseverity":"INFO","thread_id":1778366208,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"QvSocket: Connected to server as user: 'Personal\\Me' for document: '/app/' on socket 172.17.0.2:9076 <-> 172.17.0.1:53070 with ttl: 0"}
{"timestamp":"2019-03-21T07:48:22.667Z","log_type":"System","logseverity":"INFO","thread_id":1795151616,"user_id":"Personal\\Me","tenant_id":"default","app_id":"0","message":"DOC loading: Loaded session app SessionApp_61ff6691-6af0-4fe5-98ae-c46c00d29864."}
{"timestamp":"2019-03-21T07:48:22.693Z","log_type":"System","logseverity":"INFO","thread_id":1778366208,"user_id":"Internal\\Engine","tenant_id":"default","app_id":"","message":"StdServer: OnRemoteClosed entered for socket 172.17.0.2:9076 <-> 172.17.0.1:53070, user: Personal\\Me, app: SessionApp_61ff6691-6af0-4fe5-98ae-c46c00d29864."}
{"timestamp":"2019-03-21T07:48:22.693Z","log_type":"System","logseverity":"INFO","thread_id":1803544320,"user_id":"Personal\\Me","tenant_id":"default","app_id":"","message":"Session stop reason: Socket closed by client"}
{"timestamp":"2019-03-21T07:48:26.091Z","log_type":"System","logseverity":"INFO","thread_id":1803544320,"user_id":"Personal\\Me","tenant_id":"","app_id":"","message":"DOC loading: Unloading document SessionApp_61ff6691-6af0-4fe5-98ae-c46c00d29864, state UNLOADING."}


When i run this command docker exec -it <CONTAINER ID> sh -c "ls /data" and get below error:
PS C:\Project\QlikCore_data\core-get-started-master> docker exec -it 8c0838f58783 sh -c "ls /data"
ls: /data: No such file or directory

**Comment by wennmo** [comment]
So the last command shows that the `/data` folder is not actually mounted into the engine container, which leads to that when loading data from `movies.csv` the file/folder is not found inside of the container. I suggest that you try to share your `C` drive again in Docker for Windows by unchecking and checking the box again. You will also need to run `docker-compose down` for the running containers and then start them again `ACCEPT_EULA=yes docker-compose up -d`. I have seen similar problems like this before when e.g. domain password has been changed.

**Comment by kokyeesiang** [comment]
Hi @wennmo ,
**ACCEPT_EULA=yes docker-compose up -d** this command doesn't work for me to start the container. Currently am using **docker run -p 19076:9076 qlikcore/engine:12.345.0 -S AcceptEULA=yes** this command to start container. Am i missing something in the command in order to mount the **/data** folder? Or how to mount the /data folder with docker command?

Thanks.

**Comment by wennmo** [comment]
Ah ok, yes the volume mount for `/data` is declared in the `docker-compose.yml` file so if you want to use docker run instead you will need to run something like `docker run -p 19076:9076 -d -v $(pwd)/data:/data qlikcore/engine:12.345.0 -S AcceptEULA=yes`.

What shell are you starting the container from? If you are unable to pass env variable `ACCEPT_EULA` to the docker-compose command, you can always set it directly to `yes` in the docker-compose.yml file e.g. `command: -S AcceptEULA=yes`.

**Comment by kokyeesiang** [comment]
Hi @wennmo ,

I am using Windows PowerShell. 
This is what i get when i run **docker run -p 19076:9076 -d -v $(pwd)/data:/data qlikcore/engine:12.345.0 -S AcceptEULA=yes** : 
PS C:\Project\QlikCore_data\core-get-started-master> docker run -p 19076:9076 -d -v $(pwd)/data:/data qlikcore/engine:12
.345.0 -S AcceptEULA=yes
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: invalid reference format.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

There is command error when i run this.

**Comment by wennmo** [comment]
Hi @kokyeesiang, if you are using powershell then try replacing `$(pwd)` with `${PWD}`. Different syntax in powershell compared to bash. I think you should try to get `docker-compose` up and running as well, since that will help you a lot when spinning up multiple containers or volumes.

**Comment by wennmo** [comment]
Hi @kokyeesiang, did you get it running? Let us know if you are still experiencing problems.

**Comment by wennmo** [comment]
Closing issue due to inactivity. Feel free to reopen if problem still exists.
